/*
 * CursesSharp
 * 
 * Copyright 2009 Robert Konklewski
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * www.gnu.org/licenses/>.
 * 
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#if defined(CURSES_WIDE)
# if defined(HAVE_NCURSESW_NCURSES_H)
#  include <ncursesw/ncurses.h>
# endif
#endif
#if defined(HAVE_NCURSES_H)
# include <ncurses.h>
#endif
#if defined(HAVE_CURSES_H)
# include <curses.h>
#endif

#include <stdio.h>
#include <tchar.h>


#define GEN_ATTR(x) fprintf_s(OUT, "\t\tpublic const uint " #x " = 0x%.8xU;\n", (unsigned int)(A_ ## x))
#define GEN_ACS(x) fprintf_s(OUT, "\t\tpublic const uint " #x " = 0x%.8xU;\n", (unsigned int)(ACS_ ## x))
#define GEN_COLOR(x) fprintf_s(OUT, "\t\tpublic const short " #x " = 0x%x;\n", (short)(COLOR_ ## x))
#define GEN_KEY(x) fprintf_s(OUT, "\t\tpublic const int " #x " = 0x%.3x;\n", (unsigned int)(KEY_ ## x))
#define GEN_MMASK(x) fprintf_s(OUT, "\t\t" #x " = 0x%.8lxU", (x))

int _tmain(int argc, TCHAR **argv)
{
	errno_t err;  
	FILE* OUT;

	if (argc < 2)
		return -1;

	err = _tfopen_s(&OUT, argv[1], _T("wt"));

	if (err != 0)
		return -1;

#ifndef WIN32
	initscr();
#endif

	_ftprintf_s(OUT, _T("// File generated by attrgen\n"));
	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("#pragma warning disable 1591\n"));
	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("namespace CursesSharp\n"));
	_ftprintf_s(OUT, _T("{\n"));

	_ftprintf_s(OUT, _T("\t// Character attributes\n"));
	_ftprintf_s(OUT, _T("\tpublic static class Attrs\n"));
	_ftprintf_s(OUT, _T("\t{\n"));
	GEN_ATTR(NORMAL);
	GEN_ATTR(ALTCHARSET);
	GEN_ATTR(BLINK);
	GEN_ATTR(BOLD);
	GEN_ATTR(DIM);
	GEN_ATTR(INVIS);
	GEN_ATTR(PROTECT);
	GEN_ATTR(REVERSE);
	GEN_ATTR(STANDOUT);
	GEN_ATTR(UNDERLINE);
	_ftprintf_s(OUT, _T("\t\t// Attribute masks\n"));
	GEN_ATTR(ATTRIBUTES);
	GEN_ATTR(CHARTEXT);
	GEN_ATTR(COLOR);
	_ftprintf_s(OUT, _T("\t}\n"));

	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("\t// Line drawing characters\n"));
	_ftprintf_s(OUT, _T("\tpublic static class Acs\n"));
	_ftprintf_s(OUT, _T("\t{\n"));
	GEN_ACS(BLOCK);
	GEN_ACS(BOARD);
	GEN_ACS(BTEE);
	GEN_ACS(BULLET);
	GEN_ACS(CKBOARD);
	GEN_ACS(DARROW);
	GEN_ACS(DEGREE);
	GEN_ACS(DIAMOND);
	GEN_ACS(GEQUAL);
	GEN_ACS(HLINE);
	GEN_ACS(LANTERN);
	GEN_ACS(LARROW);
	GEN_ACS(LEQUAL);
	GEN_ACS(LLCORNER);
	GEN_ACS(LRCORNER);
	GEN_ACS(LTEE);
	GEN_ACS(NEQUAL);
	GEN_ACS(PI);
	GEN_ACS(PLMINUS);
	GEN_ACS(PLUS);
	GEN_ACS(RARROW);
	GEN_ACS(RTEE);
	GEN_ACS(S1);
	GEN_ACS(S3);
	GEN_ACS(S7);
	GEN_ACS(S9);
	GEN_ACS(STERLING);
	GEN_ACS(TTEE);
	GEN_ACS(UARROW);
	GEN_ACS(ULCORNER);
	GEN_ACS(URCORNER);
	GEN_ACS(VLINE);
	_ftprintf_s(OUT, _T("\t}\n"));

	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("\t// Colors\n"));
	_ftprintf_s(OUT, _T("\tpublic static class Colors\n"));
	_ftprintf_s(OUT, _T("\t{\n"));
	GEN_COLOR(BLACK);
	GEN_COLOR(BLUE);
	GEN_COLOR(GREEN);
	GEN_COLOR(CYAN);
	GEN_COLOR(RED);
	GEN_COLOR(MAGENTA);
	GEN_COLOR(YELLOW);
	GEN_COLOR(WHITE);
	_ftprintf_s(OUT, _T("\t}\n"));

	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("\t// Keys\n"));
	_ftprintf_s(OUT, _T("\tpublic static class Keys\n"));
	_ftprintf_s(OUT, _T("\t{\n"));
	GEN_KEY(BREAK);
	GEN_KEY(DOWN);
	GEN_KEY(UP);
	GEN_KEY(LEFT);
	GEN_KEY(RIGHT);
	GEN_KEY(HOME);
	GEN_KEY(BACKSPACE);
	GEN_KEY(F0);
	GEN_KEY(DL);
	GEN_KEY(IL);
	GEN_KEY(DC);
	GEN_KEY(IC);
	GEN_KEY(EIC);
	GEN_KEY(CLEAR);
	GEN_KEY(EOS);
	GEN_KEY(EOL);
	GEN_KEY(SF);
	GEN_KEY(SR);
	GEN_KEY(NPAGE);
	GEN_KEY(PPAGE);
	GEN_KEY(STAB);
	GEN_KEY(CTAB);
	GEN_KEY(CATAB);
	GEN_KEY(ENTER);
	GEN_KEY(SRESET);
	GEN_KEY(RESET);
	GEN_KEY(PRINT);
	GEN_KEY(LL);
	GEN_KEY(A1);
	GEN_KEY(A3);
	GEN_KEY(B2);
	GEN_KEY(C1);
	GEN_KEY(C3);
	GEN_KEY(BTAB);
	GEN_KEY(BEG);
	GEN_KEY(CANCEL);
	GEN_KEY(CLOSE);
	GEN_KEY(COMMAND);
	GEN_KEY(COPY);
	GEN_KEY(CREATE);
	GEN_KEY(END);
	GEN_KEY(EXIT);
	GEN_KEY(FIND);
	GEN_KEY(HELP);
	GEN_KEY(MARK);
	GEN_KEY(MESSAGE);
	GEN_KEY(MOUSE);
	GEN_KEY(MOVE);
	GEN_KEY(NEXT);
	GEN_KEY(OPEN);
	GEN_KEY(OPTIONS);
	GEN_KEY(PREVIOUS);
	GEN_KEY(REDO);
	GEN_KEY(REFERENCE);
	GEN_KEY(REFRESH);
	GEN_KEY(REPLACE);
	GEN_KEY(RESIZE);
	GEN_KEY(RESTART);
	GEN_KEY(RESUME);
	GEN_KEY(SAVE);
	GEN_KEY(SBEG);
	GEN_KEY(SCANCEL);
	GEN_KEY(SCOMMAND);
	GEN_KEY(SCOPY);
	GEN_KEY(SCREATE);
	GEN_KEY(SDC);
	GEN_KEY(SDL);
	GEN_KEY(SELECT);
	GEN_KEY(SEND);
	GEN_KEY(SEOL);
	GEN_KEY(SEXIT);
	GEN_KEY(SFIND);
	GEN_KEY(SHELP);
	GEN_KEY(SHOME);
	GEN_KEY(SIC);
	GEN_KEY(SLEFT);
	GEN_KEY(SMESSAGE);
	GEN_KEY(SMOVE);
	GEN_KEY(SNEXT);
	GEN_KEY(SOPTIONS);
	GEN_KEY(SPREVIOUS);
	GEN_KEY(SPRINT);
	GEN_KEY(SREDO);
	GEN_KEY(SREPLACE);
	GEN_KEY(SRIGHT);
	GEN_KEY(SRSUME);
	GEN_KEY(SSAVE);
	GEN_KEY(SSUSPEND);
	GEN_KEY(SUNDO);
	GEN_KEY(SUSPEND);
	GEN_KEY(UNDO);
	_ftprintf_s(OUT, _T("\n"));
	_ftprintf_s(OUT, _T("\t\tpublic static int KEY_F(int n)\n"));
	_ftprintf_s(OUT, _T("\t\t{\n"));
	_ftprintf_s(OUT, _T("\t\t\treturn Keys.F0 + n;\n"));
	_ftprintf_s(OUT, _T("\t\t}\n"));
	_ftprintf_s(OUT, _T("\n"));
	GEN_KEY(MIN);
	GEN_KEY(MAX);
	_ftprintf_s(OUT, _T("\t}\n"));

	_ftprintf_s(OUT, _T("\n"));

	_ftprintf_s(OUT, _T("\t// Mouse event masks\n"));
	_ftprintf_s(OUT, _T("\t[System.FlagsAttribute]\n"));
	_ftprintf_s(OUT, _T("\tpublic enum MouseState : uint\n"));
	_ftprintf_s(OUT, _T("\t{\n"));
	GEN_MMASK(BUTTON1_PRESSED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON1_RELEASED);		_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON1_CLICKED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON1_DOUBLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON1_TRIPLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON2_PRESSED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON2_RELEASED);		_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON2_CLICKED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON2_DOUBLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON2_TRIPLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON3_PRESSED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON3_RELEASED);		_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON3_CLICKED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON3_DOUBLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON3_TRIPLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON4_PRESSED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON4_RELEASED);		_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON4_CLICKED);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON4_DOUBLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON4_TRIPLE_CLICKED);	_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON_SHIFT);			_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON_CTRL);				_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(BUTTON_ALT);				_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(ALL_MOUSE_EVENTS);		_ftprintf_s(OUT, _T(",\n"));
	GEN_MMASK(REPORT_MOUSE_POSITION);	_ftprintf_s(OUT, _T("\n"));
	_ftprintf_s(OUT, _T("\t}\n"));

	_ftprintf_s(OUT, _T("}\n"));

#ifndef WIN32
	endwin();
#endif

	if (OUT)
	{
		err = fclose(OUT);
	}

	return 0;
}
